# Generated by Django 4.1 on 2022-08-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrisur', '0002_alter_category_description_alter_healthdrink_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta', models.CharField(max_length=50)),
                ('descuento', models.IntegerField()),
            ],
        ),
    ]
