# Generated by Django 4.0.6 on 2022-08-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrisur', '0003_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosotros', models.CharField(max_length=50)),
                ('profesion', models.CharField(max_length=50)),
            ],
        ),
    ]
