# Generated by Django 4.0.6 on 2022-08-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrisur', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='container',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='healthdrink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
