# Generated by Django 4.1 on 2022-08-24 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrisur', '0005_category_image_container_image_healthdrink_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='container',
            name='image',
        ),
    ]
